#!/usr/bin/env node
/**
 * generate_poseidon_sol.js
 *
 * Generates contracts/src/lib/Poseidon.sol from circomlib's official constants
 * (non-optimised variant: C[t*(RF+RP)], M[t][t]).
 *
 * Run AFTER: cd circuits && npm install
 * Usage:    node scripts/generate_poseidon_sol.js
 * Output:   contracts/src/lib/Poseidon.sol
 *
 * The generated file is committed. Regenerate whenever circomlib is updated and
 * re-run cross-client tests (Rust + circomlib JS + Solidity) to verify agreement.
 */

const path = require("path");
const fs   = require("fs");

const raw = require(
    path.join(__dirname, "../circuits/node_modules/circomlibjs/src/poseidon_constants.js")
).default;

const P = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;

function toHex(v) {
    // v may be a hex string "0x..." or a decimal string
    const bn = typeof v === "string" && v.startsWith("0x")
        ? BigInt(v)
        : BigInt(v);
    return "0x" + bn.toString(16).padStart(64, "0");
}

// Build PoseidonT<t+1> for nInputs inputs (state size t = nInputs+1)
function generate(nInputs) {
    const t   = nInputs + 1;
    const idx = t - 2;          // zero-indexed in circomlib arrays
    const RF  = 8;
    const RP  = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68][idx];

    const C = raw.C[idx].map(toHex);   // length = t * (RF + RP)
    const M = raw.M[idx].map(r => r.map(toHex));

    // Solidity constant declarations
    const cDecls = C.map((v, i) => `    uint256 private constant C${i} = ${v};`).join("\n");
    const mDecls = [];
    for (let i = 0; i < t; i++) {
        for (let j = 0; j < t; j++) {
            mDecls.push(`    uint256 private constant M${i}${j} = ${M[i][j]};`);
        }
    }

    // Build permutation body: t state variables
    const stateVars = Array.from({length: t}, (_, i) => `s${i}`);
    const inputArgs = Array.from({length: nInputs}, (_, i) => `uint256 input${i}`);

    // Initial state: s0 = 0 (capacity), s1..sN = inputs
    const initLines = [
        `        uint256 s0 = 0;`,
        ...Array.from({length: nInputs}, (_, i) => `        uint256 s${i+1} = input${i};`)
    ].join("\n");

    function addRoundConstant(roundBase) {
        return stateVars.map((s, j) =>
            `        ${s} = addmod(${s}, C${roundBase + j}, P);`
        ).join("\n");
    }

    // Inline x^5 = x * x^4 = x * (x^2)^2 — eliminates function-call overhead per round.
    function sboxInline(s) {
        return [
            `        {`,
            `            uint256 _x2 = mulmod(${s}, ${s}, P);`,
            `            ${s} = mulmod(mulmod(_x2, _x2, P), ${s}, P);`,
            `        }`
        ].join("\n");
    }

    function sboxAll() {
        return stateVars.map(s => sboxInline(s)).join("\n");
    }

    function sboxFirst() {
        return sboxInline("s0");
    }

    function mds() {
        // Wrap in a block so n0/n1/n2 don't collide across rounds in Solidity scope.
        const lines = ["        {"];
        for (let i = 0; i < t; i++) {
            let expr = stateVars.reduce((acc, s, j) => {
                const term = `mulmod(M${j}${i}, ${s}, P)`;
                return j === 0 ? term : `addmod(${acc}, ${term}, P)`;
            }, "");
            lines.push(`            uint256 n${i} = ${expr};`);
        }
        for (let i = 0; i < t; i++) {
            lines.push(`            s${i} = n${i};`);
        }
        lines.push("        }");
        return lines.join("\n");
    }

    const rounds = [];
    let cIdx = 0;

    // Full rounds (first RF/2)
    for (let r = 0; r < RF / 2; r++) {
        rounds.push(`        // Full round ${r}`);
        rounds.push(addRoundConstant(cIdx));
        rounds.push(sboxAll());
        rounds.push(mds());
        cIdx += t;
    }

    // Partial rounds
    for (let r = 0; r < RP; r++) {
        rounds.push(`        // Partial round ${r}`);
        rounds.push(addRoundConstant(cIdx));
        rounds.push(sboxFirst());
        rounds.push(mds());
        cIdx += t;
    }

    // Full rounds (last RF/2)
    for (let r = 0; r < RF / 2; r++) {
        rounds.push(`        // Full round ${RF / 2 + r}`);
        rounds.push(addRoundConstant(cIdx));
        rounds.push(sboxAll());
        rounds.push(mds());
        cIdx += t;
    }

    const returnVar = `s0`;

    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// PoseidonT${t} — Poseidon hash over BN254 with t=${t} (${nInputs} input${nInputs > 1 ? "s" : ""}).
//
// GENERATED by scripts/generate_poseidon_sol.js from circomlib poseidon_constants.js.
// DO NOT EDIT MANUALLY. Regenerate with: node scripts/generate_poseidon_sol.js
//
// Parameters:
//   Field : BN254 scalar field
//           p = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001
//   t     : ${t}   (state size)
//   RF    : ${RF}  (full rounds)
//   RP    : ${RP}  (partial rounds)
//   Alpha : 5  (S-box x^5)
//   MDS   : Cauchy matrix from circomlib poseidon_constants.js
//
// Cross-verification: output MUST match:
//   - circomlib poseidon([a, b]) for identical inputs
//   - light-poseidon poseidon${nInputs}(a, b) (Rust, prover/)
//
// If these diverge, proof verification will fail silently. Run:
//   forge test --match-test testPoseidonVectors -vvv

library PoseidonT${t} {
    uint256 private constant P =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Round constants — C[i] corresponds to state element i % ${t} in round i / ${t}
${cDecls}

    // MDS matrix — M[row][col]
${mDecls.join("\n")}

    /// @notice Hash ${nInputs} field element${nInputs > 1 ? "s" : ""}.
    /// @dev Inputs must be canonical field elements (< P). Reverts if any input >= P.
    function hash(${inputArgs.join(", ")}) internal pure returns (uint256) {
${initLines}

${rounds.join("\n")}

        return ${returnVar};
    }
}
`;
}

const outDir = path.join(__dirname, "../contracts/src/lib");
fs.mkdirSync(outDir, { recursive: true });

// PoseidonT3 — 2 inputs, used for Merkle tree hashing
const t3 = generate(2);
fs.writeFileSync(path.join(outDir, "Poseidon.sol"), t3);
console.log("[generate] contracts/src/lib/Poseidon.sol (PoseidonT3, 2 inputs)");
console.log("[generate] Run 'cd contracts && forge build' to verify compilation.");
console.log("[generate] Run 'forge test --match-test testPoseidonVectors' to cross-verify.");
