#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="$(cd "$(dirname "$0")/.." && pwd)/build/circuits"
CIRCUITS_DIR="$(cd "$(dirname "$0")/../circuits" && pwd)"
WITHDRAW_DIR="$BUILD_DIR/withdraw"
PASS=0
FAIL=0

require_build() {
    if [ ! -f "$WITHDRAW_DIR/withdraw.zkey" ]; then
        echo "[test] Build artifacts not found. Run scripts/compile.sh first."
        exit 1
    fi
}

run_proof() {
    local label="$1"
    local input_file="$2"
    local expect_fail="${3:-0}"

    local wtns="$BUILD_DIR/test_${label}.wtns"
    local proof="$BUILD_DIR/test_${label}_proof.json"
    local public="$BUILD_DIR/test_${label}_public.json"

    if node "$WITHDRAW_DIR/withdraw_js/generate_witness.js" \
            "$WITHDRAW_DIR/withdraw_js/withdraw.wasm" \
            "$input_file" "$wtns" 2>/dev/null; then
        if npx snarkjs plonk prove "$WITHDRAW_DIR/withdraw.zkey" "$wtns" "$proof" "$public" 2>/dev/null; then
            if npx snarkjs plonk verify "$WITHDRAW_DIR/withdraw_vkey.json" "$public" "$proof" 2>/dev/null; then
                if [ "$expect_fail" -eq 1 ]; then
                    echo "[FAIL] $label — expected rejection but proof verified"
                    FAIL=$((FAIL + 1))
                else
                    echo "[PASS] $label"
                    PASS=$((PASS + 1))
                fi
                return
            fi
        fi
    fi

    if [ "$expect_fail" -eq 1 ]; then
        echo "[PASS] $label — correctly rejected"
        PASS=$((PASS + 1))
    else
        echo "[FAIL] $label — expected valid proof"
        FAIL=$((FAIL + 1))
    fi
}

write_input() {
    local file="$1"
    local content="$2"
    echo "$content" > "$file"
}

require_build

TMPDIR_TEST=$(mktemp -d)
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# ── Test vectors ────────────────────────────────────────────────────────────
# These values must be consistent: commitment = Poseidon(DOMAIN_C, secret, nullifier)
# and the Merkle path must lead to root.
# For initial smoke testing we use pre-computed values generated by the prover tests.

SECRET="1234567890123456789012345678901234567890123456789012345678901234"
NULLIFIER="9876543210987654321098765432109876543210987654321098765432109876"
CHAIN_ID="1"
CONTRACT="0x1234567890123456789012345678901234567890"

# The prover integration tests generate valid Merkle paths. Until those run,
# the circuit tests validate the constraint structure using the witness generator.

# ── Valid witness (requires pre-computed Merkle path from prover) ───────────
VALID_INPUT="$TMPDIR_TEST/valid.json"
cat > "$VALID_INPUT" << 'ENDJSON'
{
  "_note": "Replace with output from prover::tests::generate_test_vector()",
  "secret":           "1",
  "nullifier":        "2",
  "pathElements":     ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],
  "pathIndices":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  "root":             "REPLACE_WITH_COMPUTED_ROOT",
  "nullifier_hash":   "REPLACE_WITH_COMPUTED_NULLIFIER_HASH",
  "recipient":        "12345",
  "chain_id":         "1",
  "contract_address": "54321"
}
ENDJSON

echo "[test] NOTE: Valid witness test requires pre-computed values from Rust prover."
echo "[test] Run 'cargo test generate_test_vector -- --nocapture' in prover/ first."
echo ""

# ── Invalid witness tests ───────────────────────────────────────────────────
# These test that the constraint system rejects malformed inputs.

WRONG_SECRET="$TMPDIR_TEST/wrong_secret.json"
cat > "$WRONG_SECRET" << 'ENDJSON'
{
  "secret":           "999",
  "nullifier":        "2",
  "pathElements":     ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],
  "pathIndices":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  "root":             "REPLACE_WITH_COMPUTED_ROOT",
  "nullifier_hash":   "REPLACE_WITH_COMPUTED_NULLIFIER_HASH",
  "recipient":        "12345",
  "chain_id":         "1",
  "contract_address": "54321"
}
ENDJSON

WRONG_PATH="$TMPDIR_TEST/wrong_path.json"
cat > "$WRONG_PATH" << 'ENDJSON'
{
  "secret":           "1",
  "nullifier":        "2",
  "pathElements":     ["1","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],
  "pathIndices":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  "root":             "REPLACE_WITH_COMPUTED_ROOT",
  "nullifier_hash":   "REPLACE_WITH_COMPUTED_NULLIFIER_HASH",
  "recipient":        "12345",
  "chain_id":         "1",
  "contract_address": "54321"
}
ENDJSON

WRONG_NULLIFIER="$TMPDIR_TEST/wrong_nullifier.json"
cat > "$WRONG_NULLIFIER" << 'ENDJSON'
{
  "secret":           "1",
  "nullifier":        "999",
  "pathElements":     ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],
  "pathIndices":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  "root":             "REPLACE_WITH_COMPUTED_ROOT",
  "nullifier_hash":   "REPLACE_WITH_COMPUTED_NULLIFIER_HASH",
  "recipient":        "12345",
  "chain_id":         "1",
  "contract_address": "54321"
}
ENDJSON

WRONG_ROOT="$TMPDIR_TEST/wrong_root.json"
cat > "$WRONG_ROOT" << 'ENDJSON'
{
  "secret":           "1",
  "nullifier":        "2",
  "pathElements":     ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"],
  "pathIndices":      [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  "root":             "99999999999999999999999999999999999999999999",
  "nullifier_hash":   "REPLACE_WITH_COMPUTED_NULLIFIER_HASH",
  "recipient":        "12345",
  "chain_id":         "1",
  "contract_address": "54321"
}
ENDJSON

run_proof "wrong_secret"    "$WRONG_SECRET"    1
run_proof "wrong_path"      "$WRONG_PATH"      1
run_proof "wrong_nullifier" "$WRONG_NULLIFIER" 1
run_proof "wrong_root"      "$WRONG_ROOT"      1

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
